Repository friends-of-reactphp/mysql, pull requests merged in 2018-10, with the labels that each got.

#80 Add exception message
  src/Factory.php
Labels: easy pick, maintenance, new feature

#82 Add warningCount to QueryResult
  src/Commands/QueryCommand.php
  src/Io/Connection.php
  src/Io/Parser.php
  src/QueryResult.php
  tests/NoResultQueryTest.php
Labels: new feature

#83 Fix parsing error message during handshake (Too many connections)
  src/Io/Parser.php
  tests/Io/ParserTest.php
Labels: bug

#84 Support cancellation of pending connection attempts
  README.md
  composer.json
  src/Factory.php
  tests/FactoryTest.php
Labels: new feature

#87 Add new createLazyConnection() method to only connect only on demand (on first command)
  README.md
  composer.json
  examples/01-query.php
  examples/02-query-stream.php
  src/Factory.php
  src/Io/LazyConnection.php
  tests/FactoryTest.php
  tests/Io/LazyConnectionTest.php
  tests/ResultQueryTest.php
Labels: new feature
