Repository friends-of-reactphp/mysql, pull requests merged in 2021-08, with the labels that each got.

#136 Simplify usage by supporting new Socket API and use new deafult loop in test suite
  README.md
  composer.json
  src/Factory.php
  tests/FactoryTest.php
  tests/NoResultQueryTest.php
  tests/ResultQueryTest.php
Labels: new feature

#137 Replace array() with [] and minor clean up
  README.md
  examples/12-slow-stream.php
  src/Commands/AuthenticateCommand.php
  src/ConnectionInterface.php
  src/Factory.php
  src/Io/Connection.php
  src/Io/LazyConnection.php
  src/Io/Parser.php
  src/Io/Query.php
  src/Io/QueryStream.php
  tests/BaseTestCase.php
  tests/FactoryTest.php
  tests/Io/ConnectionTest.php
  tests/Io/LazyConnectionTest.php
  tests/Io/QueryStreamTest.php
  tests/Io/QueryTest.php
  tests/ResultQueryTest.php
Labels: easy pick, maintenance

#138 Support URI scheme to create connection
  src/Factory.php
  tests/FactoryTest.php
Labels: new feature

#139 Provide limited support for `NO_BACKSLASH_ESCAPES` SQL mode
  src/Io/Query.php
  tests/Io/QueryTest.php
  tests/ResultQueryTest.php
Labels: bug, new feature

#141 Improve error reporting, include MySQL URI and socket error codes in all connection errors
  README.md
  examples/01-query.php
  examples/02-query-stream.php
  examples/11-interactive.php
  examples/12-slow-stream.php
  src/Factory.php
  src/Io/Connection.php
  src/Io/Parser.php
  tests/FactoryTest.php
  tests/Io/ConnectionTest.php
  tests/Io/ParserTest.php
Labels: new feature
