Repository friends-of-reactphp/mysql, pull requests merged in 2023-11, with the labels that each got.

#180 Run tests on PHP 8.3 and update test suite
  .github/workflows/ci.yml
  composer.json
Labels: new feature

#181 Improve CI workflow to await database
  tests/wait-for-mysql.sh
Labels: maintenance

#182 Reduce default idle time to 1ms
  README.md
  examples/01-query.php
  examples/02-query-stream.php
  src/Factory.php
  src/Io/LazyConnection.php
  tests/FactoryTest.php
  tests/Io/LazyConnectionTest.php
Labels: new feature

#183 Use Promise v3 template types
  README.md
  src/ConnectionInterface.php
  src/Factory.php
Labels: new feature

#184 Fix typos in documentation
  CHANGELOG.md
  README.md
  examples/12-slow-stream.php
  src/ConnectionInterface.php
  src/Factory.php
  src/Io/Buffer.php
  src/Io/Connection.php
  src/Io/Parser.php
  src/Io/Query.php
  tests/ResultQueryTest.php
Labels: documentation

#185 Hello `0.7.x` development branch
  README.md
Labels: maintenance

#186 Simplify API, add new `MysqlClient` and remove `Factory` and `ConnectionInterface`
  README.md
  examples/01-query.php
  examples/02-query-stream.php
  examples/11-interactive.php
  examples/12-slow-stream.php
  src/ConnectionInterface.php
  src/Io/Connection.php
  src/Io/Factory.php
  src/Io/LazyConnection.php
  src/MysqlClient.php
  tests/BaseTestCase.php
  tests/Io/FactoryTest.php
  tests/MysqlClientTest.php
  tests/NoResultQueryTest.php
  tests/ResultQueryTest.php
Labels: new feature, BC break

#187 Rename `QueryResult` to `MysqlResult`
  README.md
  examples/01-query.php
  examples/11-interactive.php
  src/Io/Connection.php
  src/MysqlClient.php
  src/MysqlResult.php
  tests/MysqlClientTest.php
  tests/NoResultQueryTest.php
  tests/ResultQueryTest.php
Labels: new feature, BC break

#188 Rename `MySQL` namespace to `Mysql`
  README.md
  composer.json
  examples/01-query.php
  examples/02-query-stream.php
  examples/11-interactive.php
  examples/12-slow-stream.php
  src/Commands/AbstractCommand.php
  src/Commands/AuthenticateCommand.php
  src/Commands/CommandInterface.php
  src/Commands/PingCommand.php
  src/Commands/QueryCommand.php
  src/Commands/QuitCommand.php
  src/Exception.php
  src/Io/Buffer.php
  src/Io/Connection.php
  src/Io/Constants.php
  src/Io/Executor.php
  src/Io/Factory.php
  src/Io/Parser.php
  src/Io/Query.php
  src/Io/QueryStream.php
  src/MysqlClient.php
  src/MysqlResult.php
  tests/BaseTestCase.php
  tests/Commands/AuthenticateCommandTest.php
  tests/Io/BufferTest.php
  tests/Io/ConnectionTest.php
  tests/Io/FactoryTest.php
  tests/Io/ParserTest.php
  tests/Io/QueryStreamTest.php
  tests/Io/QueryTest.php
  tests/MysqlClientTest.php
  tests/NoResultQueryTest.php
  tests/ResultQueryTest.php
Labels: new feature, BC break

#189 Consistently emit close event after quit even if server rejects
  README.md
  src/Io/Connection.php
  src/MysqlClient.php
  tests/Io/ConnectionTest.php
  tests/MysqlClientTest.php
  tests/NoResultQueryTest.php
Labels: bug, new feature
